# Generated by Django 4.2.7 on 2023-11-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoModel',
            new_name='Mijozlar',
        ),
    ]
